---
version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` file in the `opbeans` directory
    directory: "/opbeans/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/apm-agent-java"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/apm-agent-java"

  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "elastic/observablt-ci"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      github-actions:
        patterns:
          - "*"