---
name: build
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make build
      - name: test
        run: make test
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: target/*.xml
