name: release

on:
  push:
    branches: [ "main" ]
  create:
    tags: [ "v*" ]

permissions:
  contents: read

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: elastic/apm-pipeline-library/.github/actions/docker-login@current
      with:
        registry: docker.io
        secret: secret/apm-team/ci/elastic-observability-dockerhub
        url: ${{ secrets.VAULT_ADDR }}
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}

    - name: Set version if tags
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Run publish
      run: make publish

    - id: docker-envs
      run: make docker-envs

    - name: Attest image
      uses: github-early-access/generate-build-provenance@main
      with:
        subject-name: ${{ steps.docker-envs.outputs.image }}
        subject-digest: ${{ steps.docker-envs.outputs.digest }}
        push-to-registry: true
