---
## Workflow to process the JUnit test results and add a report to the checks.
name: Test Report
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/test-report
        with:
          artifact: test-results            # artifact name
          name: JUnit Tests                 # Name of the check run which will be created
          path: "**/*.xml"                  # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
